<?php
$pages = $block->getPages();
$selectedPages = explode(',', $block->getData('data_options'));
?>


<h1 style="font-weight: bold"><?php echo $this->getData('title'); ?></h1>
<ul>
    <?php if ($this->getData('displayMode') === 'allPages'): ?>
        <?php foreach ($pages as $page) : ?>
            <li><a href="<?php echo $block->getPageUrl($page->getId()); ?>"> <?php echo $page->getTitle(); ?></a>
            </li>

        <?php endforeach; ?>

    <?php elseif ($this->getData('displayMode') === 'specificPages') : ?>
        <?php foreach ($selectedPages as $page) : ?>
            <li><a href="<?php echo $block->getPageUrl($page); ?>"> <?php echo $page; ?></a>
            </li>
        <?php endforeach; ?>

    <?php endif; ?>
</ul>

