<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $stockQuantity = $block->getData('view_model'); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) : ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) : ?>
                <div class="field qty">
                    <button name="qty-minus" class="substract-item-quantity-button" type="button">-</button>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               min="0"
                               value="<?= $block->getProductDefaultQty() * 1 ?>"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                    <button name="qty-plus" class="add-item-quantity-button" type="button">+</button>

                    <?php if ($block->displayProductStockStatus()) : ?>
                        <?php if ($_product->isAvailable()) : ?>
                            <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                                <span>&#10003;<?= $block->escapeHtml(__('In stock')) ?></span>
                                <span class="product-stock-quantity"><?= $stockQuantity->getStockQty($_product->getSku()); ?> items available</span>
                            </div>
                        <?php else : ?>
                            <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                                <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>

                </div>

            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }


</script>
