<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $stockQuantity = $block->getData('view_model'); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) : ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) : ?>
                <div id="custom-qty" class="field qty" data-bind="scope: 'qty-counter'">
                    <div  class="control">
                        <!-- ko template: getTemplate() --><!-- /ko -->
                        <script type="text/x-magento-init">
                            {
                                "#custom-qty": {
                                    "Magento_Ui/js/core/app": {
                                        "components": {
                                            "qty-counter": {
                                                "component": "qty-counter",
                                                "config": {
                                                    "qty": <?php echo $block->getProductDefaultQty() * 1 ?>,
                                                    "stockLeft": <?= $stockQuantity->getStockQty($_product->getSku()); ?>
                                                }
                                            }
                                         }
                                    }
                                }
                            }
                        </script>
                    </div>


                    <?php if ($block->displayProductStockStatus()) : ?>
                        <?php if ($_product->isAvailable()) : ?>
                            <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                                <span>&#10003;<?= $block->escapeHtml(__('In stock')) ?></span>
                                <span class="product-stock-quantity"><?= $stockQuantity->getStockQty($_product->getSku()); ?></span>
                                <span class="product-stock-quantity">items available</span>
                            </div>
                        <?php else : ?>
                            <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                                <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>

                </div>

            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }

</script>

