<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();
$allowedAttributes = $block->getData("view_model");

?>
<?php if ($_additional = $block->getAdditionalData()) : ?>

    <?php $listOfProductAttributeCodes = array_keys($_additional) ?>

    <div class="product-attribute-list">
        <ul>

            <?php foreach ($allowedAttributes->getAttributes($_additional) as $attribute) : ?>
                <li><span class="attribute-label"><?= $block->escapeHtml($attribute['label']) ?>
                        : </span><span><?= /* @noEscape */
                        $_helper->productAttribute($_product, $attribute['value'], $attribute['code']) ?></span>
                </li>
            <?php endforeach; ?>


        </ul>
    </div>
<?php endif; ?>
