<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();
$allowedAttribute = $block->getData("view_model");
?>
<?php if ($_additional = $block->getAdditionalData()) : ?>
    <div class="product-attribute-list">
        <ul>
            <?php foreach ($_additional as $_data) : ?>
                <?php if ($allowedAttribute->isAllowed($_data['code'])) : ?>
                    <li><span class="attribute-label"><?= $block->escapeHtml($_data['label']) ?>: </span><span><?= /* @noEscape */
                            $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></span></li>
                <?php endif; ?>

            <?php endforeach; ?>
        </ul>
    </div>

<?php endif; ?>
